{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-supervisor.serviceAccountName" . }}
  # The tenant's namespace, because that is where the pods it supervises live
  # and where its SA needs to be for the (cluster-scoped) binding to be
  # meaningful in the audit log.
  namespace: {{ include "node-supervisor.namespace" . }}
  labels:
    {{- include "node-supervisor.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
