apiVersion: apps/v1
kind: Deployment
metadata:
  name: lora-swap-max1-deployment
  labels:
    app: lora-swap-max1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lora-swap-max1
  template:
    metadata:
      labels:
        app: lora-swap-max1
        snapshot-agent: "true"
        timeslice.io/job-id: "lora-test-max1"
    spec:
      hostIPC: true
      hostPID: true  # Required for GPU-CR IPC matching
      containers:
      - name: lora-swap
        image: asia-southeast1-docker.pkg.dev/edwinhernandez-gke-dev/snapshot-example/lora-swap-client-max1:latest # Replace with your actual image tag
        command: ["python3"]
        args: ["test_lora_swap_max1.py"]
        securityContext:
          runAsUser: 0
        imagePullPolicy: Always
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: AGENT_ENDPOINT
          value: "$(NODE_IP):9001"
        - name: JOB_ID
          value: "lora-test-max1"
        - name: GROUP
          value: "lora-group"
        - name: GPU_VENDOR
          value: "NVIDIA"
        - name: GPUCR_NUM_THREADS
          value: "16"
        - name: GPUCR_SHM_GB
          value: "60"
        - name: GPUCR_STAGING_MB
          value: "1024"
        - name: VLLM_ALLOW_INSECURE_SERIALIZATION
          value: "1"
        - name: LD_PRELOAD
          value: "/usr/local/lib/vGPU-NVIDIA.so"
        - name: VLLM_ENABLE_V1_MULTIPROCESSING
          value: "0"
        - name: LD_LIBRARY_PATH
          value: "/usr/local/cuda/lib64"
        - name: PYTORCH_NO_CUDA_MEMORY_CACHING
          value: "1"
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: CUDA_LAUNCH_BLOCKING
          value: "1"
        volumeMounts:
        - name: huge-ckpt
          mountPath: /mnt/huge-ckpt
        resources:
          claims:
            - name: gpus-for-pod
          requests:
            memory: "4Gi"
            hugepages-2Mi: "40Gi"
          limits:
            memory: "4Gi"
            hugepages-2Mi: "40Gi" 
      volumes:
      - name: huge-ckpt
        hostPath:
          path: /var/tmp/huge-ckpt
          type: DirectoryOrCreate
      resourceClaims:
      - name: gpus-for-pod
        resourceClaimName: shared-two-gpus-claim
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
