// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: host_command.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command names a host command in an ack.
type Command int32

const (
	Command_COMMAND_UNSPECIFIED Command = 0
	Command_COMMAND_VACATE      Command = 1
	Command_COMMAND_RESUME      Command = 2
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "COMMAND_UNSPECIFIED",
		1: "COMMAND_VACATE",
		2: "COMMAND_RESUME",
	}
	Command_value = map[string]int32{
		"COMMAND_UNSPECIFIED": 0,
		"COMMAND_VACATE":      1,
		"COMMAND_RESUME":      2,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_host_command_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_host_command_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_host_command_proto_rawDescGZIP(), []int{0}
}

// Outcome is the result of a host command, for the host or for one guest.
type Outcome int32

const (
	Outcome_OUTCOME_UNSPECIFIED Outcome = 0
	// Every guest is suspended: the host is clear.
	Outcome_OUTCOME_VACATED Outcome = 1
	// Every guest was resumed and marked ready.
	Outcome_OUTCOME_RESUMED Outcome = 2
	// The command failed; error says why. For Vacate the host is not clear.
	Outcome_OUTCOME_FAILED Outcome = 3
	// The command's epoch is lower than one the host has already seen. The host
	// did nothing. HostAck.current_epoch holds the higher epoch.
	Outcome_OUTCOME_STALE_EPOCH Outcome = 4
	// The command was superseded by a command with a higher epoch.
	Outcome_OUTCOME_ABORTED Outcome = 5
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_VACATED",
		2: "OUTCOME_RESUMED",
		3: "OUTCOME_FAILED",
		4: "OUTCOME_STALE_EPOCH",
		5: "OUTCOME_ABORTED",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"OUTCOME_VACATED":     1,
		"OUTCOME_RESUMED":     2,
		"OUTCOME_FAILED":      3,
		"OUTCOME_STALE_EPOCH": 4,
		"OUTCOME_ABORTED":     5,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_host_command_proto_enumTypes[1].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_host_command_proto_enumTypes[1]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_host_command_proto_rawDescGZIP(), []int{1}
}

type VacateRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupId string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// The real node the command is for. A host refuses a command for another
	// node.
	NodeName string `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Epoch    int64  `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Absolute time by which every guest must be suspended: T = notice + N - K.
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VacateRequest) Reset() {
	*x = VacateRequest{}
	mi := &file_host_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VacateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VacateRequest) ProtoMessage() {}

func (x *VacateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VacateRequest.ProtoReflect.Descriptor instead.
func (*VacateRequest) Descriptor() ([]byte, []int) {
	return file_host_command_proto_rawDescGZIP(), []int{0}
}

func (x *VacateRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *VacateRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *VacateRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *VacateRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type ResumeRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GroupId  string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	NodeName string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Epoch    int64                  `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Absolute time by which every guest should be resumed.
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_host_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_host_command_proto_rawDescGZIP(), []int{1}
}

func (x *ResumeRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ResumeRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ResumeRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ResumeRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

// GuestResult is the outcome of a command for one guest.
type GuestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guest         string                 `protobuf:"bytes,1,opt,name=guest,proto3" json:"guest,omitempty"`
	Outcome       Outcome                `protobuf:"varint,2,opt,name=outcome,proto3,enum=timeslice_hostcommand.v1alpha1.Outcome" json:"outcome,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestResult) Reset() {
	*x = GuestResult{}
	mi := &file_host_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestResult) ProtoMessage() {}

func (x *GuestResult) ProtoReflect() protoreflect.Message {
	mi := &file_host_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestResult.ProtoReflect.Descriptor instead.
func (*GuestResult) Descriptor() ([]byte, []int) {
	return file_host_command_proto_rawDescGZIP(), []int{2}
}

func (x *GuestResult) GetGuest() string {
	if x != nil {
		return x.Guest
	}
	return ""
}

func (x *GuestResult) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *GuestResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HostAck acknowledges a command. The orchestrator acts on an ack only when
// its epoch and command match the command it is waiting for.
type HostAck struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeName string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// The epoch of the command this ack answers.
	Epoch   int64   `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Command Command `protobuf:"varint,3,opt,name=command,proto3,enum=timeslice_hostcommand.v1alpha1.Command" json:"command,omitempty"`
	Outcome Outcome `protobuf:"varint,4,opt,name=outcome,proto3,enum=timeslice_hostcommand.v1alpha1.Outcome" json:"outcome,omitempty"`
	// The highest epoch the host has seen.
	CurrentEpoch  int64          `protobuf:"varint,5,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	Guests        []*GuestResult `protobuf:"bytes,6,rep,name=guests,proto3" json:"guests,omitempty"`
	Error         string         `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostAck) Reset() {
	*x = HostAck{}
	mi := &file_host_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostAck) ProtoMessage() {}

func (x *HostAck) ProtoReflect() protoreflect.Message {
	mi := &file_host_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostAck.ProtoReflect.Descriptor instead.
func (*HostAck) Descriptor() ([]byte, []int) {
	return file_host_command_proto_rawDescGZIP(), []int{3}
}

func (x *HostAck) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HostAck) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *HostAck) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_COMMAND_UNSPECIFIED
}

func (x *HostAck) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *HostAck) GetCurrentEpoch() int64 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

func (x *HostAck) GetGuests() []*GuestResult {
	if x != nil {
		return x.Guests
	}
	return nil
}

func (x *HostAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_host_command_proto protoreflect.FileDescriptor

const file_host_command_proto_rawDesc = "" +
	"\n" +
	"\x12host_command.proto\x12\x1etimeslice_hostcommand.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n" +
	"\rVacateRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x03R\x05epoch\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"\x95\x01\n" +
	"\rResumeRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x03R\x05epoch\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"|\n" +
	"\vGuestResult\x12\x14\n" +
	"\x05guest\x18\x01 \x01(\tR\x05guest\x12A\n" +
	"\aoutcome\x18\x02 \x01(\x0e2'.timeslice_hostcommand.v1alpha1.OutcomeR\aoutcome\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xc2\x02\n" +
	"\aHostAck\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12A\n" +
	"\acommand\x18\x03 \x01(\x0e2'.timeslice_hostcommand.v1alpha1.CommandR\acommand\x12A\n" +
	"\aoutcome\x18\x04 \x01(\x0e2'.timeslice_hostcommand.v1alpha1.OutcomeR\aoutcome\x12#\n" +
	"\rcurrent_epoch\x18\x05 \x01(\x03R\fcurrentEpoch\x12C\n" +
	"\x06guests\x18\x06 \x03(\v2+.timeslice_hostcommand.v1alpha1.GuestResultR\x06guests\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error*J\n" +
	"\aCommand\x12\x17\n" +
	"\x13COMMAND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCOMMAND_VACATE\x10\x01\x12\x12\n" +
	"\x0eCOMMAND_RESUME\x10\x02*\x8e\x01\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOUTCOME_VACATED\x10\x01\x12\x13\n" +
	"\x0fOUTCOME_RESUMED\x10\x02\x12\x12\n" +
	"\x0eOUTCOME_FAILED\x10\x03\x12\x17\n" +
	"\x13OUTCOME_STALE_EPOCH\x10\x04\x12\x13\n" +
	"\x0fOUTCOME_ABORTED\x10\x052\xd8\x01\n" +
	"\x12HostCommandService\x12`\n" +
	"\x06Vacate\x12-.timeslice_hostcommand.v1alpha1.VacateRequest\x1a'.timeslice_hostcommand.v1alpha1.HostAck\x12`\n" +
	"\x06Resume\x12-.timeslice_hostcommand.v1alpha1.ResumeRequest\x1a'.timeslice_hostcommand.v1alpha1.HostAckBGZEgithub.com/edwinhr716/guest-kubelet/api/hostcommand/v1alpha1;v1alpha1b\x06proto3"

var (
	file_host_command_proto_rawDescOnce sync.Once
	file_host_command_proto_rawDescData []byte
)

func file_host_command_proto_rawDescGZIP() []byte {
	file_host_command_proto_rawDescOnce.Do(func() {
		file_host_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_host_command_proto_rawDesc), len(file_host_command_proto_rawDesc)))
	})
	return file_host_command_proto_rawDescData
}

var file_host_command_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_host_command_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_host_command_proto_goTypes = []any{
	(Command)(0),                  // 0: timeslice_hostcommand.v1alpha1.Command
	(Outcome)(0),                  // 1: timeslice_hostcommand.v1alpha1.Outcome
	(*VacateRequest)(nil),         // 2: timeslice_hostcommand.v1alpha1.VacateRequest
	(*ResumeRequest)(nil),         // 3: timeslice_hostcommand.v1alpha1.ResumeRequest
	(*GuestResult)(nil),           // 4: timeslice_hostcommand.v1alpha1.GuestResult
	(*HostAck)(nil),               // 5: timeslice_hostcommand.v1alpha1.HostAck
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_host_command_proto_depIdxs = []int32{
	6, // 0: timeslice_hostcommand.v1alpha1.VacateRequest.deadline:type_name -> google.protobuf.Timestamp
	6, // 1: timeslice_hostcommand.v1alpha1.ResumeRequest.deadline:type_name -> google.protobuf.Timestamp
	1, // 2: timeslice_hostcommand.v1alpha1.GuestResult.outcome:type_name -> timeslice_hostcommand.v1alpha1.Outcome
	0, // 3: timeslice_hostcommand.v1alpha1.HostAck.command:type_name -> timeslice_hostcommand.v1alpha1.Command
	1, // 4: timeslice_hostcommand.v1alpha1.HostAck.outcome:type_name -> timeslice_hostcommand.v1alpha1.Outcome
	4, // 5: timeslice_hostcommand.v1alpha1.HostAck.guests:type_name -> timeslice_hostcommand.v1alpha1.GuestResult
	2, // 6: timeslice_hostcommand.v1alpha1.HostCommandService.Vacate:input_type -> timeslice_hostcommand.v1alpha1.VacateRequest
	3, // 7: timeslice_hostcommand.v1alpha1.HostCommandService.Resume:input_type -> timeslice_hostcommand.v1alpha1.ResumeRequest
	5, // 8: timeslice_hostcommand.v1alpha1.HostCommandService.Vacate:output_type -> timeslice_hostcommand.v1alpha1.HostAck
	5, // 9: timeslice_hostcommand.v1alpha1.HostCommandService.Resume:output_type -> timeslice_hostcommand.v1alpha1.HostAck
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_host_command_proto_init() }
func file_host_command_proto_init() {
	if File_host_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_host_command_proto_rawDesc), len(file_host_command_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_host_command_proto_goTypes,
		DependencyIndexes: file_host_command_proto_depIdxs,
		EnumInfos:         file_host_command_proto_enumTypes,
		MessageInfos:      file_host_command_proto_msgTypes,
	}.Build()
	File_host_command_proto = out.File
	file_host_command_proto_goTypes = nil
	file_host_command_proto_depIdxs = nil
}
