// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: host_command.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HostRole selects which pods on the node a host command targets.
type HostRole int32

const (
	HostRole_HOST_ROLE_UNSPECIFIED HostRole = 0
	// Pods of the foreground (donor) job.
	HostRole_HOST_ROLE_FOREGROUND HostRole = 1
	// Background (guest) pods.
	HostRole_HOST_ROLE_BACKGROUND HostRole = 2
)

// Enum value maps for HostRole.
var (
	HostRole_name = map[int32]string{
		0: "HOST_ROLE_UNSPECIFIED",
		1: "HOST_ROLE_FOREGROUND",
		2: "HOST_ROLE_BACKGROUND",
	}
	HostRole_value = map[string]int32{
		"HOST_ROLE_UNSPECIFIED": 0,
		"HOST_ROLE_FOREGROUND":  1,
		"HOST_ROLE_BACKGROUND":  2,
	}
)

func (x HostRole) Enum() *HostRole {
	p := new(HostRole)
	*p = x
	return p
}

func (x HostRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostRole) Descriptor() protoreflect.EnumDescriptor {
	return file_host_command_proto_enumTypes[0].Descriptor()
}

func (HostRole) Type() protoreflect.EnumType {
	return &file_host_command_proto_enumTypes[0]
}

func (x HostRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostRole.Descriptor instead.
func (HostRole) EnumDescriptor() ([]byte, []int) {
	return file_host_command_proto_rawDescGZIP(), []int{0}
}

type HostCommandOutcome int32

const (
	HostCommandOutcome_HOST_COMMAND_OUTCOME_UNSPECIFIED HostCommandOutcome = 0
	// SuspendAll finished: no target holds the accelerator (also when the host
	// had no target).
	HostCommandOutcome_HOST_COMMAND_OUTCOME_CLEAR HostCommandOutcome = 1
	// ResumeAll finished: every target resumed.
	HostCommandOutcome_HOST_COMMAND_OUTCOME_RESUMED HostCommandOutcome = 2
	// At least one target failed; see targets.
	HostCommandOutcome_HOST_COMMAND_OUTCOME_FAILED HostCommandOutcome = 3
	// The epoch was fenced off; nothing ran.
	HostCommandOutcome_HOST_COMMAND_OUTCOME_STALE_EPOCH HostCommandOutcome = 4
)

// Enum value maps for HostCommandOutcome.
var (
	HostCommandOutcome_name = map[int32]string{
		0: "HOST_COMMAND_OUTCOME_UNSPECIFIED",
		1: "HOST_COMMAND_OUTCOME_CLEAR",
		2: "HOST_COMMAND_OUTCOME_RESUMED",
		3: "HOST_COMMAND_OUTCOME_FAILED",
		4: "HOST_COMMAND_OUTCOME_STALE_EPOCH",
	}
	HostCommandOutcome_value = map[string]int32{
		"HOST_COMMAND_OUTCOME_UNSPECIFIED": 0,
		"HOST_COMMAND_OUTCOME_CLEAR":       1,
		"HOST_COMMAND_OUTCOME_RESUMED":     2,
		"HOST_COMMAND_OUTCOME_FAILED":      3,
		"HOST_COMMAND_OUTCOME_STALE_EPOCH": 4,
	}
)

func (x HostCommandOutcome) Enum() *HostCommandOutcome {
	p := new(HostCommandOutcome)
	*p = x
	return p
}

func (x HostCommandOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostCommandOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_host_command_proto_enumTypes[1].Descriptor()
}

func (HostCommandOutcome) Type() protoreflect.EnumType {
	return &file_host_command_proto_enumTypes[1]
}

func (x HostCommandOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostCommandOutcome.Descriptor instead.
func (HostCommandOutcome) EnumDescriptor() ([]byte, []int) {
	return file_host_command_proto_rawDescGZIP(), []int{1}
}

type SuspendAllRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group is the time-slice group the command is issued for.
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// role selects the targets. UNSPECIFIED is treated as BACKGROUND.
	Role HostRole `protobuf:"varint,2,opt,name=role,proto3,enum=snapshot_agent.v1alpha1.HostRole" json:"role,omitempty"`
	// epoch fences the command; see HostCommandService.
	Epoch int64 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// deadline is absolute. Every target should be suspended by then.
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendAllRequest) Reset() {
	*x = SuspendAllRequest{}
	mi := &file_host_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendAllRequest) ProtoMessage() {}

func (x *SuspendAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendAllRequest.ProtoReflect.Descriptor instead.
func (*SuspendAllRequest) Descriptor() ([]byte, []int) {
	return file_host_command_proto_rawDescGZIP(), []int{0}
}

func (x *SuspendAllRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SuspendAllRequest) GetRole() HostRole {
	if x != nil {
		return x.Role
	}
	return HostRole_HOST_ROLE_UNSPECIFIED
}

func (x *SuspendAllRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *SuspendAllRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type ResumeAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Role          HostRole               `protobuf:"varint,2,opt,name=role,proto3,enum=snapshot_agent.v1alpha1.HostRole" json:"role,omitempty"`
	Epoch         int64                  `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeAllRequest) Reset() {
	*x = ResumeAllRequest{}
	mi := &file_host_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeAllRequest) ProtoMessage() {}

func (x *ResumeAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeAllRequest.ProtoReflect.Descriptor instead.
func (*ResumeAllRequest) Descriptor() ([]byte, []int) {
	return file_host_command_proto_rawDescGZIP(), []int{1}
}

func (x *ResumeAllRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ResumeAllRequest) GetRole() HostRole {
	if x != nil {
		return x.Role
	}
	return HostRole_HOST_ROLE_UNSPECIFIED
}

func (x *ResumeAllRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ResumeAllRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

// TargetResult reports one target of a host command.
type TargetResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target names the target (the guest).
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// error is empty when the target succeeded.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetResult) Reset() {
	*x = TargetResult{}
	mi := &file_host_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetResult) ProtoMessage() {}

func (x *TargetResult) ProtoReflect() protoreflect.Message {
	mi := &file_host_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetResult.ProtoReflect.Descriptor instead.
func (*TargetResult) Descriptor() ([]byte, []int) {
	return file_host_command_proto_rawDescGZIP(), []int{2}
}

func (x *TargetResult) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TargetResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HostCommandAck is the host's answer to a host command.
type HostCommandAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// epoch is the epoch this ack is for. The caller drops an ack whose epoch
	// is not the one it is waiting for.
	Epoch   int64              `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Outcome HostCommandOutcome `protobuf:"varint,2,opt,name=outcome,proto3,enum=snapshot_agent.v1alpha1.HostCommandOutcome" json:"outcome,omitempty"`
	Targets []*TargetResult    `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	// error summarises a FAILED or STALE_EPOCH outcome.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostCommandAck) Reset() {
	*x = HostCommandAck{}
	mi := &file_host_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCommandAck) ProtoMessage() {}

func (x *HostCommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_host_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCommandAck.ProtoReflect.Descriptor instead.
func (*HostCommandAck) Descriptor() ([]byte, []int) {
	return file_host_command_proto_rawDescGZIP(), []int{3}
}

func (x *HostCommandAck) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *HostCommandAck) GetOutcome() HostCommandOutcome {
	if x != nil {
		return x.Outcome
	}
	return HostCommandOutcome_HOST_COMMAND_OUTCOME_UNSPECIFIED
}

func (x *HostCommandAck) GetTargets() []*TargetResult {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *HostCommandAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_host_command_proto protoreflect.FileDescriptor

const file_host_command_proto_rawDesc = "" +
	"\n" +
	"\x12host_command.proto\x12\x17snapshot_agent.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n" +
	"\x11SuspendAllRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x125\n" +
	"\x04role\x18\x02 \x01(\x0e2!.snapshot_agent.v1alpha1.HostRoleR\x04role\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x03R\x05epoch\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"\xad\x01\n" +
	"\x10ResumeAllRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x125\n" +
	"\x04role\x18\x02 \x01(\x0e2!.snapshot_agent.v1alpha1.HostRoleR\x04role\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x03R\x05epoch\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"<\n" +
	"\fTargetResult\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc4\x01\n" +
	"\x0eHostCommandAck\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12E\n" +
	"\aoutcome\x18\x02 \x01(\x0e2+.snapshot_agent.v1alpha1.HostCommandOutcomeR\aoutcome\x12?\n" +
	"\atargets\x18\x03 \x03(\v2%.snapshot_agent.v1alpha1.TargetResultR\atargets\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error*Y\n" +
	"\bHostRole\x12\x19\n" +
	"\x15HOST_ROLE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14HOST_ROLE_FOREGROUND\x10\x01\x12\x18\n" +
	"\x14HOST_ROLE_BACKGROUND\x10\x02*\xc3\x01\n" +
	"\x12HostCommandOutcome\x12$\n" +
	" HOST_COMMAND_OUTCOME_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aHOST_COMMAND_OUTCOME_CLEAR\x10\x01\x12 \n" +
	"\x1cHOST_COMMAND_OUTCOME_RESUMED\x10\x02\x12\x1f\n" +
	"\x1bHOST_COMMAND_OUTCOME_FAILED\x10\x03\x12$\n" +
	" HOST_COMMAND_OUTCOME_STALE_EPOCH\x10\x042\xd8\x01\n" +
	"\x12HostCommandService\x12a\n" +
	"\n" +
	"SuspendAll\x12*.snapshot_agent.v1alpha1.SuspendAllRequest\x1a'.snapshot_agent.v1alpha1.HostCommandAck\x12_\n" +
	"\tResumeAll\x12).snapshot_agent.v1alpha1.ResumeAllRequest\x1a'.snapshot_agent.v1alpha1.HostCommandAckB\\ZZgithub.com/llm-d-incubation/llm-d-rl-time-slicing/pkg/snapshot-agent/api/v1alpha1;v1alpha1b\x06proto3"

var (
	file_host_command_proto_rawDescOnce sync.Once
	file_host_command_proto_rawDescData []byte
)

func file_host_command_proto_rawDescGZIP() []byte {
	file_host_command_proto_rawDescOnce.Do(func() {
		file_host_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_host_command_proto_rawDesc), len(file_host_command_proto_rawDesc)))
	})
	return file_host_command_proto_rawDescData
}

var file_host_command_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_host_command_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_host_command_proto_goTypes = []any{
	(HostRole)(0),                 // 0: snapshot_agent.v1alpha1.HostRole
	(HostCommandOutcome)(0),       // 1: snapshot_agent.v1alpha1.HostCommandOutcome
	(*SuspendAllRequest)(nil),     // 2: snapshot_agent.v1alpha1.SuspendAllRequest
	(*ResumeAllRequest)(nil),      // 3: snapshot_agent.v1alpha1.ResumeAllRequest
	(*TargetResult)(nil),          // 4: snapshot_agent.v1alpha1.TargetResult
	(*HostCommandAck)(nil),        // 5: snapshot_agent.v1alpha1.HostCommandAck
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_host_command_proto_depIdxs = []int32{
	0, // 0: snapshot_agent.v1alpha1.SuspendAllRequest.role:type_name -> snapshot_agent.v1alpha1.HostRole
	6, // 1: snapshot_agent.v1alpha1.SuspendAllRequest.deadline:type_name -> google.protobuf.Timestamp
	0, // 2: snapshot_agent.v1alpha1.ResumeAllRequest.role:type_name -> snapshot_agent.v1alpha1.HostRole
	6, // 3: snapshot_agent.v1alpha1.ResumeAllRequest.deadline:type_name -> google.protobuf.Timestamp
	1, // 4: snapshot_agent.v1alpha1.HostCommandAck.outcome:type_name -> snapshot_agent.v1alpha1.HostCommandOutcome
	4, // 5: snapshot_agent.v1alpha1.HostCommandAck.targets:type_name -> snapshot_agent.v1alpha1.TargetResult
	2, // 6: snapshot_agent.v1alpha1.HostCommandService.SuspendAll:input_type -> snapshot_agent.v1alpha1.SuspendAllRequest
	3, // 7: snapshot_agent.v1alpha1.HostCommandService.ResumeAll:input_type -> snapshot_agent.v1alpha1.ResumeAllRequest
	5, // 8: snapshot_agent.v1alpha1.HostCommandService.SuspendAll:output_type -> snapshot_agent.v1alpha1.HostCommandAck
	5, // 9: snapshot_agent.v1alpha1.HostCommandService.ResumeAll:output_type -> snapshot_agent.v1alpha1.HostCommandAck
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_host_command_proto_init() }
func file_host_command_proto_init() {
	if File_host_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_host_command_proto_rawDesc), len(file_host_command_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_host_command_proto_goTypes,
		DependencyIndexes: file_host_command_proto_depIdxs,
		EnumInfos:         file_host_command_proto_enumTypes,
		MessageInfos:      file_host_command_proto_msgTypes,
	}.Build()
	File_host_command_proto = out.File
	file_host_command_proto_goTypes = nil
	file_host_command_proto_depIdxs = nil
}
