// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: host_command.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostCommandService_SuspendAll_FullMethodName = "/snapshot_agent.v1alpha1.HostCommandService/SuspendAll"
	HostCommandService_ResumeAll_FullMethodName  = "/snapshot_agent.v1alpha1.HostCommandService/ResumeAll"
)

// HostCommandServiceClient is the client API for HostCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostCommandService is the host-level command endpoint of the snapshot
// agent. The agent serves it next to SnapshotAgentService, on the same port.
// The orchestrator is the only caller: on a foreground Acquire it tells every
// host of the group to vacate by a deadline and grants only after every host
// acked; on a foreground Yield that lends the accelerator it tells every host
// to resume.
//
// The agent enumerates its targets on its own node at command time (pods
// with the requested role). It never decides; it only executes and acks.
//
// Both calls block until the host has finished the command (or the caller
// gives up). The response is the ack. Calling again with the same epoch and
// the same command joins the running command, or returns the recorded ack
// if it already finished.
//
// Epoch fencing, per host:
//   - epoch lower than the highest seen: STALE_EPOCH, nothing runs;
//   - same epoch, same command: join or replay (idempotent);
//   - same epoch, other command: STALE_EPOCH;
//   - higher epoch, same command while one runs: the running command is
//     adopted by the new epoch (it keeps running; the deadline is replaced);
//   - higher epoch, other command while one runs: the new command starts
//     once the running one has finished (a half-done checkpoint or restore
//     is never cancelled).
type HostCommandServiceClient interface {
	// SuspendAll suspends every target on the host. The host runs, per target
	// and one at a time: mark the target not ready and wait for the
	// confirmation, then suspend it. HOST_COMMAND_OUTCOME_CLEAR means no target
	// on the host holds the accelerator: this is what "host is clear" means to
	// the orchestrator.
	SuspendAll(ctx context.Context, in *SuspendAllRequest, opts ...grpc.CallOption) (*HostCommandAck, error)
	// ResumeAll resumes every suspended target on the host: resume, then mark
	// it ready.
	ResumeAll(ctx context.Context, in *ResumeAllRequest, opts ...grpc.CallOption) (*HostCommandAck, error)
}

type hostCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostCommandServiceClient(cc grpc.ClientConnInterface) HostCommandServiceClient {
	return &hostCommandServiceClient{cc}
}

func (c *hostCommandServiceClient) SuspendAll(ctx context.Context, in *SuspendAllRequest, opts ...grpc.CallOption) (*HostCommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostCommandAck)
	err := c.cc.Invoke(ctx, HostCommandService_SuspendAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostCommandServiceClient) ResumeAll(ctx context.Context, in *ResumeAllRequest, opts ...grpc.CallOption) (*HostCommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostCommandAck)
	err := c.cc.Invoke(ctx, HostCommandService_ResumeAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostCommandServiceServer is the server API for HostCommandService service.
// All implementations must embed UnimplementedHostCommandServiceServer
// for forward compatibility.
//
// HostCommandService is the host-level command endpoint of the snapshot
// agent. The agent serves it next to SnapshotAgentService, on the same port.
// The orchestrator is the only caller: on a foreground Acquire it tells every
// host of the group to vacate by a deadline and grants only after every host
// acked; on a foreground Yield that lends the accelerator it tells every host
// to resume.
//
// The agent enumerates its targets on its own node at command time (pods
// with the requested role). It never decides; it only executes and acks.
//
// Both calls block until the host has finished the command (or the caller
// gives up). The response is the ack. Calling again with the same epoch and
// the same command joins the running command, or returns the recorded ack
// if it already finished.
//
// Epoch fencing, per host:
//   - epoch lower than the highest seen: STALE_EPOCH, nothing runs;
//   - same epoch, same command: join or replay (idempotent);
//   - same epoch, other command: STALE_EPOCH;
//   - higher epoch, same command while one runs: the running command is
//     adopted by the new epoch (it keeps running; the deadline is replaced);
//   - higher epoch, other command while one runs: the new command starts
//     once the running one has finished (a half-done checkpoint or restore
//     is never cancelled).
type HostCommandServiceServer interface {
	// SuspendAll suspends every target on the host. The host runs, per target
	// and one at a time: mark the target not ready and wait for the
	// confirmation, then suspend it. HOST_COMMAND_OUTCOME_CLEAR means no target
	// on the host holds the accelerator: this is what "host is clear" means to
	// the orchestrator.
	SuspendAll(context.Context, *SuspendAllRequest) (*HostCommandAck, error)
	// ResumeAll resumes every suspended target on the host: resume, then mark
	// it ready.
	ResumeAll(context.Context, *ResumeAllRequest) (*HostCommandAck, error)
	mustEmbedUnimplementedHostCommandServiceServer()
}

// UnimplementedHostCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostCommandServiceServer struct{}

func (UnimplementedHostCommandServiceServer) SuspendAll(context.Context, *SuspendAllRequest) (*HostCommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendAll not implemented")
}
func (UnimplementedHostCommandServiceServer) ResumeAll(context.Context, *ResumeAllRequest) (*HostCommandAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeAll not implemented")
}
func (UnimplementedHostCommandServiceServer) mustEmbedUnimplementedHostCommandServiceServer() {}
func (UnimplementedHostCommandServiceServer) testEmbeddedByValue()                            {}

// UnsafeHostCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostCommandServiceServer will
// result in compilation errors.
type UnsafeHostCommandServiceServer interface {
	mustEmbedUnimplementedHostCommandServiceServer()
}

func RegisterHostCommandServiceServer(s grpc.ServiceRegistrar, srv HostCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedHostCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostCommandService_ServiceDesc, srv)
}

func _HostCommandService_SuspendAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostCommandServiceServer).SuspendAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostCommandService_SuspendAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostCommandServiceServer).SuspendAll(ctx, req.(*SuspendAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostCommandService_ResumeAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostCommandServiceServer).ResumeAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostCommandService_ResumeAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostCommandServiceServer).ResumeAll(ctx, req.(*ResumeAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostCommandService_ServiceDesc is the grpc.ServiceDesc for HostCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snapshot_agent.v1alpha1.HostCommandService",
	HandlerType: (*HostCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SuspendAll",
			Handler:    _HostCommandService_SuspendAll_Handler,
		},
		{
			MethodName: "ResumeAll",
			Handler:    _HostCommandService_ResumeAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "host_command.proto",
}
