// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: snapshot_agent.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Deprecated: Marked as deprecated in snapshot_agent.proto.
type Backend int32

const (
	Backend_BACKEND_UNSPECIFIED Backend = 0
	Backend_BACKEND_CUDA        Backend = 1
)

// Enum value maps for Backend.
var (
	Backend_name = map[int32]string{
		0: "BACKEND_UNSPECIFIED",
		1: "BACKEND_CUDA",
	}
	Backend_value = map[string]int32{
		"BACKEND_UNSPECIFIED": 0,
		"BACKEND_CUDA":        1,
	}
)

func (x Backend) Enum() *Backend {
	p := new(Backend)
	*p = x
	return p
}

func (x Backend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Backend) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[0].Descriptor()
}

func (Backend) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[0]
}

func (x Backend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Backend.Descriptor instead.
func (Backend) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{0}
}

// App identifies the HTTP API dialect of an application-aware workload.
// It grows only when a new HTTP dialect ships; workloads reached through a
// registered workload channel never need an entry here.
type App int32

const (
	App_APP_UNSPECIFIED App = 0
	// vLLM's dev-mode sleep API: POST /sleep?level=N, POST /wake_up?tags=...
	// Requires VLLM_SERVER_DEV_MODE=1 and --enable-sleep-mode on the server.
	App_APP_VLLM App = 1
	// SGLang's memory API: POST /release_memory_occupation and
	// POST /resume_memory_occupation (JSON body). Requires
	// --enable-memory-saver; whether suspended weights are preserved is fixed
	// at server launch by --enable-weights-cpu-backup (see SuspendMode).
	App_APP_SGLANG App = 2
)

// Enum value maps for App.
var (
	App_name = map[int32]string{
		0: "APP_UNSPECIFIED",
		1: "APP_VLLM",
		2: "APP_SGLANG",
	}
	App_value = map[string]int32{
		"APP_UNSPECIFIED": 0,
		"APP_VLLM":        1,
		"APP_SGLANG":      2,
	}
)

func (x App) Enum() *App {
	p := new(App)
	*p = x
	return p
}

func (x App) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (App) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[1].Descriptor()
}

func (App) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[1]
}

func (x App) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use App.Descriptor instead.
func (App) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{1}
}

// SuspendMode states what happens to the workload's durable state (model
// weights, optimizer state) while suspended. Region-level engine specifics
// (e.g. KV cache is discarded by engines in either mode) are handled by the
// application dialect.
type SuspendMode int32

const (
	// Use the application's default behavior.
	SuspendMode_SUSPEND_MODE_UNSPECIFIED SuspendMode = 0
	// State is preserved in host memory; Restore copies it back.
	SuspendMode_SUSPEND_MODE_OFFLOAD SuspendMode = 1
	// State is dropped; the application must re-provision it after Restore
	// (e.g. RL weight sync). Unsupported by workloads that cannot reconstruct
	// state, such as trainers.
	SuspendMode_SUSPEND_MODE_DISCARD SuspendMode = 2
)

// Enum value maps for SuspendMode.
var (
	SuspendMode_name = map[int32]string{
		0: "SUSPEND_MODE_UNSPECIFIED",
		1: "SUSPEND_MODE_OFFLOAD",
		2: "SUSPEND_MODE_DISCARD",
	}
	SuspendMode_value = map[string]int32{
		"SUSPEND_MODE_UNSPECIFIED": 0,
		"SUSPEND_MODE_OFFLOAD":     1,
		"SUSPEND_MODE_DISCARD":     2,
	}
)

func (x SuspendMode) Enum() *SuspendMode {
	p := new(SuspendMode)
	*p = x
	return p
}

func (x SuspendMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SuspendMode) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[2].Descriptor()
}

func (SuspendMode) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[2]
}

func (x SuspendMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SuspendMode.Descriptor instead.
func (SuspendMode) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{2}
}

// Outcome is the result of a completed Suspend, Resume or Kill operation.
type Outcome int32

const (
	Outcome_OUTCOME_UNSPECIFIED Outcome = 0
	// The job is checkpointed and frozen and holds no device memory.
	Outcome_OUTCOME_SUSPENDED Outcome = 1
	// The job had no process left; there was nothing to suspend.
	Outcome_OUTCOME_RELEASED Outcome = 2
	// The job is thawed and restored.
	Outcome_OUTCOME_RESUMED Outcome = 3
	// Every process of the job was killed and the kill was confirmed.
	Outcome_OUTCOME_KILLED Outcome = 4
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_SUSPENDED",
		2: "OUTCOME_RELEASED",
		3: "OUTCOME_RESUMED",
		4: "OUTCOME_KILLED",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"OUTCOME_SUSPENDED":   1,
		"OUTCOME_RELEASED":    2,
		"OUTCOME_RESUMED":     3,
		"OUTCOME_KILLED":      4,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[3].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[3]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{3}
}

// ErrorReason classifies why an operation failed or a call was refused.
type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNSPECIFIED ErrorReason = 0
	ErrorReason_DEADLINE_INFEASIBLE      ErrorReason = 1
	ErrorReason_DEADLINE_EXCEEDED        ErrorReason = 2
	ErrorReason_STALE_EPOCH              ErrorReason = 3
	ErrorReason_PRECONDITION_READINESS   ErrorReason = 4
	ErrorReason_PRECONDITION_PROBES      ErrorReason = 5
	ErrorReason_PRECONDITION_MEMORY      ErrorReason = 6
	ErrorReason_PRECONDITION_NODE        ErrorReason = 7
	ErrorReason_BACKEND_ERROR            ErrorReason = 8
	ErrorReason_VERIFY_FAILED            ErrorReason = 9
	ErrorReason_KILL_UNCONFIRMED         ErrorReason = 10
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "ERROR_REASON_UNSPECIFIED",
		1:  "DEADLINE_INFEASIBLE",
		2:  "DEADLINE_EXCEEDED",
		3:  "STALE_EPOCH",
		4:  "PRECONDITION_READINESS",
		5:  "PRECONDITION_PROBES",
		6:  "PRECONDITION_MEMORY",
		7:  "PRECONDITION_NODE",
		8:  "BACKEND_ERROR",
		9:  "VERIFY_FAILED",
		10: "KILL_UNCONFIRMED",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNSPECIFIED": 0,
		"DEADLINE_INFEASIBLE":      1,
		"DEADLINE_EXCEEDED":        2,
		"STALE_EPOCH":              3,
		"PRECONDITION_READINESS":   4,
		"PRECONDITION_PROBES":      5,
		"PRECONDITION_MEMORY":      6,
		"PRECONDITION_NODE":        7,
		"BACKEND_ERROR":            8,
		"VERIFY_FAILED":            9,
		"KILL_UNCONFIRMED":         10,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[4].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[4]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{4}
}

type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	OperationStatus_OPERATION_STATUS_PENDING     OperationStatus = 1
	OperationStatus_OPERATION_STATUS_COMPLETE    OperationStatus = 2
	OperationStatus_OPERATION_STATUS_FAILED      OperationStatus = 3
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_PENDING",
		2: "OPERATION_STATUS_COMPLETE",
		3: "OPERATION_STATUS_FAILED",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED": 0,
		"OPERATION_STATUS_PENDING":     1,
		"OPERATION_STATUS_COMPLETE":    2,
		"OPERATION_STATUS_FAILED":      3,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[5].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[5]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{5}
}

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED   JobState = 0
	JobState_JOB_STATE_IDLE          JobState = 1
	JobState_JOB_STATE_RUNNING       JobState = 2
	JobState_JOB_STATE_TRANSITIONING JobState = 3
	JobState_JOB_STATE_SAVED         JobState = 4
	JobState_JOB_STATE_FAULTED       JobState = 5
	// Checkpointed and frozen; holds no device memory.
	JobState_JOB_STATE_SUSPENDED JobState = 6
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_IDLE",
		2: "JOB_STATE_RUNNING",
		3: "JOB_STATE_TRANSITIONING",
		4: "JOB_STATE_SAVED",
		5: "JOB_STATE_FAULTED",
		6: "JOB_STATE_SUSPENDED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED":   0,
		"JOB_STATE_IDLE":          1,
		"JOB_STATE_RUNNING":       2,
		"JOB_STATE_TRANSITIONING": 3,
		"JOB_STATE_SAVED":         4,
		"JOB_STATE_FAULTED":       5,
		"JOB_STATE_SUSPENDED":     6,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[6].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[6]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{6}
}

// ProcessTarget specifies a set of process IDs (PIDs) to target.
// This is optional in some deployment modes (like 'k8s' where PIDs can be discovered automatically),
// but required in others (like 'standalone').
// In the future, we may add other target types (e.g., MemoryTarget)
// to support different backends.
type ProcessTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pids          []int32                `protobuf:"varint,1,rep,packed,name=pids,proto3" json:"pids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessTarget) Reset() {
	*x = ProcessTarget{}
	mi := &file_snapshot_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTarget) ProtoMessage() {}

func (x *ProcessTarget) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTarget.ProtoReflect.Descriptor instead.
func (*ProcessTarget) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessTarget) GetPids() []int32 {
	if x != nil {
		return x.Pids
	}
	return nil
}

type CudaBackendConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExplicitTarget *ProcessTarget         `protobuf:"bytes,1,opt,name=explicit_target,json=explicitTarget,proto3" json:"explicit_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CudaBackendConfig) Reset() {
	*x = CudaBackendConfig{}
	mi := &file_snapshot_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CudaBackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CudaBackendConfig) ProtoMessage() {}

func (x *CudaBackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CudaBackendConfig.ProtoReflect.Descriptor instead.
func (*CudaBackendConfig) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CudaBackendConfig) GetExplicitTarget() *ProcessTarget {
	if x != nil {
		return x.ExplicitTarget
	}
	return nil
}

// Configuration for the Direct Memory (process-level) backend.
//
// Experimental: this backend is driven by GPU-CR, which is itself
// experimental — expect deployment requirements and operational caveats.
// It is disabled by default: requests selecting it fail with
// FAILED_PRECONDITION unless the agent runs with
// --feature-gates=DirectMemoryBackend=true (or the FEATURE_GATES env var).
type DirectMemoryBackendConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target processes to checkpoint/restore.
	ExplicitTarget *ProcessTarget `protobuf:"bytes,1,opt,name=explicit_target,json=explicitTarget,proto3" json:"explicit_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DirectMemoryBackendConfig) Reset() {
	*x = DirectMemoryBackendConfig{}
	mi := &file_snapshot_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectMemoryBackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectMemoryBackendConfig) ProtoMessage() {}

func (x *DirectMemoryBackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectMemoryBackendConfig.ProtoReflect.Descriptor instead.
func (*DirectMemoryBackendConfig) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{2}
}

func (x *DirectMemoryBackendConfig) GetExplicitTarget() *ProcessTarget {
	if x != nil {
		return x.ExplicitTarget
	}
	return nil
}

// Configuration for the TPU (libtpu) backend. Checkpoint/restore of TPU state
// for running processes via libtpu's control-pipe protocol (gVisor's
// tpucheckpoint CLI); targets must run with LIBTPU_CHECKPOINTING_ENABLED=true.
type TpuBackendConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target processes to checkpoint/restore. Optional in 'k8s' deployment
	// mode (PIDs are discovered from the job's pods), required in 'standalone'.
	// Restore is a slice-wide rendezvous inside libtpu: all of a job's TPU
	// processes must be restored in one request, and a restore must never be
	// retried.
	ExplicitTarget *ProcessTarget `protobuf:"bytes,1,opt,name=explicit_target,json=explicitTarget,proto3" json:"explicit_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TpuBackendConfig) Reset() {
	*x = TpuBackendConfig{}
	mi := &file_snapshot_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TpuBackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TpuBackendConfig) ProtoMessage() {}

func (x *TpuBackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TpuBackendConfig.ProtoReflect.Descriptor instead.
func (*TpuBackendConfig) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{3}
}

func (x *TpuBackendConfig) GetExplicitTarget() *ProcessTarget {
	if x != nil {
		return x.ExplicitTarget
	}
	return nil
}

// AppEndpointConfig suspends/resumes an application-aware workload through
// its HTTP API. Callers using this config supply the endpoints and therefore
// know which application they deployed; `app` selects the HTTP dialect.
type AppEndpointConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	App   App                    `protobuf:"varint,1,opt,name=app,proto3,enum=snapshot_agent.v1alpha1.App" json:"app,omitempty"`
	// HTTP endpoint(s) of the application server(s), e.g. "http://localhost:8000".
	Endpoints []string `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// See SuspendMode. For APP_SGLANG this is advisory: the effective mode is
	// fixed by the server's launch flags.
	Mode SuspendMode `protobuf:"varint,3,opt,name=mode,proto3,enum=snapshot_agent.v1alpha1.SuspendMode" json:"mode,omitempty"`
	// Region tags, e.g. "weights", "kv_cache". Free-form strings validated by
	// the application; if empty, the application's full default region set is
	// used. On Snapshot, tags select what to suspend (where the application
	// supports it); on Restore, what to bring back.
	Tags          []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppEndpointConfig) Reset() {
	*x = AppEndpointConfig{}
	mi := &file_snapshot_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppEndpointConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppEndpointConfig) ProtoMessage() {}

func (x *AppEndpointConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppEndpointConfig.ProtoReflect.Descriptor instead.
func (*AppEndpointConfig) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AppEndpointConfig) GetApp() App {
	if x != nil {
		return x.App
	}
	return App_APP_UNSPECIFIED
}

func (x *AppEndpointConfig) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *AppEndpointConfig) GetMode() SuspendMode {
	if x != nil {
		return x.Mode
	}
	return SuspendMode_SUSPEND_MODE_UNSPECIFIED
}

func (x *AppEndpointConfig) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// AppChannelConfig suspends/resumes an application-aware workload through
// its registered workload channel (see WorkloadChannel). The workload is
// addressed by the request's job_id; callers need no endpoints and no
// knowledge of which application is running.
type AppChannelConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// See SuspendMode. If unspecified, the workload's registered default mode
	// is used (OFFLOAD if the workload did not declare one).
	Mode SuspendMode `protobuf:"varint,1,opt,name=mode,proto3,enum=snapshot_agent.v1alpha1.SuspendMode" json:"mode,omitempty"`
	// Region tags; see AppEndpointConfig.tags.
	Tags          []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppChannelConfig) Reset() {
	*x = AppChannelConfig{}
	mi := &file_snapshot_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppChannelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppChannelConfig) ProtoMessage() {}

func (x *AppChannelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppChannelConfig.ProtoReflect.Descriptor instead.
func (*AppChannelConfig) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AppChannelConfig) GetMode() SuspendMode {
	if x != nil {
		return x.Mode
	}
	return SuspendMode_SUSPEND_MODE_UNSPECIFIED
}

func (x *AppChannelConfig) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// MemoryRegion identifies one device-memory range owned by a process.
type MemoryRegion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PID of the process that owns the region.
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// Device virtual address of the start of the region.
	Address uint64 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
	// Length of the region in bytes.
	SizeBytes     uint64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryRegion) Reset() {
	*x = MemoryRegion{}
	mi := &file_snapshot_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryRegion) ProtoMessage() {}

func (x *MemoryRegion) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryRegion.ProtoReflect.Descriptor instead.
func (*MemoryRegion) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryRegion) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *MemoryRegion) GetAddress() uint64 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *MemoryRegion) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// Configuration for the memory-regions backend: selective checkpoint and
// restore of specific device memory ranges of a running process (GPU-CR
// cr_client with a `-s addr:size,...` spec). Regions are required on both
// Snapshot and Restore; the agent performs no discovery for this backend.
type MemoryRegionsBackendConfig struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Regions []*MemoryRegion        `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	// snapshot_name names the snapshot slot the regions are saved to
	// (Snapshot) or loaded from (Restore). Distinct names let multiple
	// snapshots of the same process coexist and be swapped on demand.
	// If empty, the request's job_id is used. Note this is deliberately NOT
	// the request's `group`: group identifies a set of related jobs for the
	// orchestrator and does not name agent-side storage.
	SnapshotName  string `protobuf:"bytes,2,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryRegionsBackendConfig) Reset() {
	*x = MemoryRegionsBackendConfig{}
	mi := &file_snapshot_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryRegionsBackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryRegionsBackendConfig) ProtoMessage() {}

func (x *MemoryRegionsBackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryRegionsBackendConfig.ProtoReflect.Descriptor instead.
func (*MemoryRegionsBackendConfig) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{7}
}

func (x *MemoryRegionsBackendConfig) GetRegions() []*MemoryRegion {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *MemoryRegionsBackendConfig) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

type BackendConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Backend:
	//
	//	*BackendConfig_Cuda
	//	*BackendConfig_AppEndpoint
	//	*BackendConfig_AppChannel
	//	*BackendConfig_DirectMemory
	//	*BackendConfig_MemoryRegions
	//	*BackendConfig_Tpu
	Backend       isBackendConfig_Backend `protobuf_oneof:"backend"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendConfig) Reset() {
	*x = BackendConfig{}
	mi := &file_snapshot_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendConfig) ProtoMessage() {}

func (x *BackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendConfig.ProtoReflect.Descriptor instead.
func (*BackendConfig) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{8}
}

func (x *BackendConfig) GetBackend() isBackendConfig_Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *BackendConfig) GetCuda() *CudaBackendConfig {
	if x != nil {
		if x, ok := x.Backend.(*BackendConfig_Cuda); ok {
			return x.Cuda
		}
	}
	return nil
}

func (x *BackendConfig) GetAppEndpoint() *AppEndpointConfig {
	if x != nil {
		if x, ok := x.Backend.(*BackendConfig_AppEndpoint); ok {
			return x.AppEndpoint
		}
	}
	return nil
}

func (x *BackendConfig) GetAppChannel() *AppChannelConfig {
	if x != nil {
		if x, ok := x.Backend.(*BackendConfig_AppChannel); ok {
			return x.AppChannel
		}
	}
	return nil
}

func (x *BackendConfig) GetDirectMemory() *DirectMemoryBackendConfig {
	if x != nil {
		if x, ok := x.Backend.(*BackendConfig_DirectMemory); ok {
			return x.DirectMemory
		}
	}
	return nil
}

func (x *BackendConfig) GetMemoryRegions() *MemoryRegionsBackendConfig {
	if x != nil {
		if x, ok := x.Backend.(*BackendConfig_MemoryRegions); ok {
			return x.MemoryRegions
		}
	}
	return nil
}

func (x *BackendConfig) GetTpu() *TpuBackendConfig {
	if x != nil {
		if x, ok := x.Backend.(*BackendConfig_Tpu); ok {
			return x.Tpu
		}
	}
	return nil
}

type isBackendConfig_Backend interface {
	isBackendConfig_Backend()
}

type BackendConfig_Cuda struct {
	Cuda *CudaBackendConfig `protobuf:"bytes,1,opt,name=cuda,proto3,oneof"`
}

type BackendConfig_AppEndpoint struct {
	AppEndpoint *AppEndpointConfig `protobuf:"bytes,2,opt,name=app_endpoint,json=appEndpoint,proto3,oneof"`
}

type BackendConfig_AppChannel struct {
	AppChannel *AppChannelConfig `protobuf:"bytes,3,opt,name=app_channel,json=appChannel,proto3,oneof"`
}

type BackendConfig_DirectMemory struct {
	// Experimental: disabled by default behind the DirectMemoryBackend
	// feature gate; see DirectMemoryBackendConfig.
	DirectMemory *DirectMemoryBackendConfig `protobuf:"bytes,4,opt,name=direct_memory,json=directMemory,proto3,oneof"`
}

type BackendConfig_MemoryRegions struct {
	MemoryRegions *MemoryRegionsBackendConfig `protobuf:"bytes,5,opt,name=memory_regions,json=memoryRegions,proto3,oneof"`
}

type BackendConfig_Tpu struct {
	Tpu *TpuBackendConfig `protobuf:"bytes,6,opt,name=tpu,proto3,oneof"`
}

func (*BackendConfig_Cuda) isBackendConfig_Backend() {}

func (*BackendConfig_AppEndpoint) isBackendConfig_Backend() {}

func (*BackendConfig_AppChannel) isBackendConfig_Backend() {}

func (*BackendConfig_DirectMemory) isBackendConfig_Backend() {}

func (*BackendConfig_MemoryRegions) isBackendConfig_Backend() {}

func (*BackendConfig_Tpu) isBackendConfig_Backend() {}

// WorkloadCapabilities is declared by a workload at registration and lets the
// agent validate and resolve snapshot parameters without knowing the
// application.
type WorkloadCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Suspend modes the workload can execute. If empty, no validation is
	// performed. A trainer that cannot reconstruct dropped state would
	// advertise only SUSPEND_MODE_OFFLOAD.
	SupportedModes []SuspendMode `protobuf:"varint,1,rep,packed,name=supported_modes,json=supportedModes,proto3,enum=snapshot_agent.v1alpha1.SuspendMode" json:"supported_modes,omitempty"`
	// Mode used when a snapshot request leaves the mode unspecified. If unset,
	// SUSPEND_MODE_OFFLOAD is used.
	DefaultMode SuspendMode `protobuf:"varint,2,opt,name=default_mode,json=defaultMode,proto3,enum=snapshot_agent.v1alpha1.SuspendMode" json:"default_mode,omitempty"`
	// Region tags the workload understands, e.g. "weights", "kv_cache".
	Tags          []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadCapabilities) Reset() {
	*x = WorkloadCapabilities{}
	mi := &file_snapshot_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadCapabilities) ProtoMessage() {}

func (x *WorkloadCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadCapabilities.ProtoReflect.Descriptor instead.
func (*WorkloadCapabilities) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{9}
}

func (x *WorkloadCapabilities) GetSupportedModes() []SuspendMode {
	if x != nil {
		return x.SupportedModes
	}
	return nil
}

func (x *WorkloadCapabilities) GetDefaultMode() SuspendMode {
	if x != nil {
		return x.DefaultMode
	}
	return SuspendMode_SUSPEND_MODE_UNSPECIFIED
}

func (x *WorkloadCapabilities) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// RegisterWorkload is the first message a workload sends on a
// WorkloadChannel stream. Re-registering a job_id replaces the previous
// stream.
type RegisterWorkload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id identifies the job this workload belongs to and must be unique
	// per agent (jobs are node-scoped; group does not namespace job IDs).
	// Snapshot/Restore requests carrying an AppChannelConfig are routed to the
	// stream registered under the same job_id.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// group is an optional identifier for a set of related jobs.
	Group         string                `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Capabilities  *WorkloadCapabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkload) Reset() {
	*x = RegisterWorkload{}
	mi := &file_snapshot_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkload) ProtoMessage() {}

func (x *RegisterWorkload) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkload.ProtoReflect.Descriptor instead.
func (*RegisterWorkload) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterWorkload) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RegisterWorkload) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *RegisterWorkload) GetCapabilities() *WorkloadCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// CommandResult acknowledges completion of an AgentCommand.
type CommandResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Ok        bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	// error is set when ok is false.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_snapshot_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WorkloadMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*WorkloadMessage_Register
	//	*WorkloadMessage_Result
	Message       isWorkloadMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadMessage) Reset() {
	*x = WorkloadMessage{}
	mi := &file_snapshot_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadMessage) ProtoMessage() {}

func (x *WorkloadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadMessage.ProtoReflect.Descriptor instead.
func (*WorkloadMessage) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{12}
}

func (x *WorkloadMessage) GetMessage() isWorkloadMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *WorkloadMessage) GetRegister() *RegisterWorkload {
	if x != nil {
		if x, ok := x.Message.(*WorkloadMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkloadMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Message.(*WorkloadMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isWorkloadMessage_Message interface {
	isWorkloadMessage_Message()
}

type WorkloadMessage_Register struct {
	Register *RegisterWorkload `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkloadMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*WorkloadMessage_Register) isWorkloadMessage_Message() {}

func (*WorkloadMessage_Result) isWorkloadMessage_Message() {}

// SnapshotCommand instructs the workload to suspend. The mode is fully
// resolved by the agent (never SUSPEND_MODE_UNSPECIFIED on the wire).
type SnapshotCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          SuspendMode            `protobuf:"varint,1,opt,name=mode,proto3,enum=snapshot_agent.v1alpha1.SuspendMode" json:"mode,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotCommand) Reset() {
	*x = SnapshotCommand{}
	mi := &file_snapshot_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotCommand) ProtoMessage() {}

func (x *SnapshotCommand) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotCommand.ProtoReflect.Descriptor instead.
func (*SnapshotCommand) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{13}
}

func (x *SnapshotCommand) GetMode() SuspendMode {
	if x != nil {
		return x.Mode
	}
	return SuspendMode_SUSPEND_MODE_UNSPECIFIED
}

func (x *SnapshotCommand) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// RestoreCommand instructs the workload to resume.
type RestoreCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreCommand) Reset() {
	*x = RestoreCommand{}
	mi := &file_snapshot_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreCommand) ProtoMessage() {}

func (x *RestoreCommand) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreCommand.ProtoReflect.Descriptor instead.
func (*RestoreCommand) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{14}
}

func (x *RestoreCommand) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// AgentCommand is pushed by the agent to a registered workload. Each command
// carries a unique command_id and is sent at most once; the workload replies
// with a CommandResult bearing the same command_id.
type AgentCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*AgentCommand_Snapshot
	//	*AgentCommand_Restore
	Command       isAgentCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_snapshot_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{15}
}

func (x *AgentCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AgentCommand) GetCommand() isAgentCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *AgentCommand) GetSnapshot() *SnapshotCommand {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *AgentCommand) GetRestore() *RestoreCommand {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_Restore); ok {
			return x.Restore
		}
	}
	return nil
}

type isAgentCommand_Command interface {
	isAgentCommand_Command()
}

type AgentCommand_Snapshot struct {
	Snapshot *SnapshotCommand `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

type AgentCommand_Restore struct {
	Restore *RestoreCommand `protobuf:"bytes,3,opt,name=restore,proto3,oneof"`
}

func (*AgentCommand_Snapshot) isAgentCommand_Command() {}

func (*AgentCommand_Restore) isAgentCommand_Command() {}

type SnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier for the job, unique per agent
	// (group does not namespace job IDs).
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// group is an optional identifier for a set of related jobs.
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// Deprecated: Use backend_config instead.
	//
	// Deprecated: Marked as deprecated in snapshot_agent.proto.
	Backend Backend `protobuf:"varint,3,opt,name=backend,proto3,enum=snapshot_agent.v1alpha1.Backend" json:"backend,omitempty"`
	// backend_config specifies the backend-specific configuration for the snapshot.
	// If omitted, the default backend (CUDA) will be used with default discovery
	// based on the deployment mode.
	BackendConfig *BackendConfig `protobuf:"bytes,4,opt,name=backend_config,json=backendConfig,proto3" json:"backend_config,omitempty"`
	// deadline is an optional absolute time by which the snapshot must finish.
	// If unset, the operation is not bounded by a deadline.
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{16}
}

func (x *SnapshotRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SnapshotRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

// Deprecated: Marked as deprecated in snapshot_agent.proto.
func (x *SnapshotRequest) GetBackend() Backend {
	if x != nil {
		return x.Backend
	}
	return Backend_BACKEND_UNSPECIFIED
}

func (x *SnapshotRequest) GetBackendConfig() *BackendConfig {
	if x != nil {
		return x.BackendConfig
	}
	return nil
}

func (x *SnapshotRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{17}
}

func (x *SnapshotResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type RestoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier for the job, unique per agent
	// (group does not namespace job IDs).
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// group is an optional identifier for a set of related jobs.
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// Deprecated: Use backend_config instead.
	//
	// Deprecated: Marked as deprecated in snapshot_agent.proto.
	Backend Backend `protobuf:"varint,3,opt,name=backend,proto3,enum=snapshot_agent.v1alpha1.Backend" json:"backend,omitempty"`
	// backend_config specifies the backend-specific configuration for the restoration.
	BackendConfig *BackendConfig `protobuf:"bytes,4,opt,name=backend_config,json=backendConfig,proto3" json:"backend_config,omitempty"`
	// deadline is an optional absolute time by which the restore must finish.
	// If unset, the operation is not bounded by a deadline.
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{18}
}

func (x *RestoreRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RestoreRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

// Deprecated: Marked as deprecated in snapshot_agent.proto.
func (x *RestoreRequest) GetBackend() Backend {
	if x != nil {
		return x.Backend
	}
	return Backend_BACKEND_UNSPECIFIED
}

func (x *RestoreRequest) GetBackendConfig() *BackendConfig {
	if x != nil {
		return x.BackendConfig
	}
	return nil
}

func (x *RestoreRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{19}
}

func (x *RestoreResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// SuspendRequest asks the agent to suspend a background (guest) job.
//
// Epoch fencing: the caller writes the epoch on the job's mirror pod as the
// annotation timeslice.io/guest-epoch before calling, and uses each epoch for
// exactly one call. A lower epoch than the last one seen is refused with
// STALE_EPOCH. The same epoch and the same call returns the same operation_id.
// The same epoch with a different call is refused with STALE_EPOCH. A higher
// epoch while an operation runs aborts the running operation.
type SuspendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier for the job, unique per agent.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// epoch fences late or duplicate calls (see above).
	Epoch int64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// deadline is the absolute time by which the operation must finish.
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendRequest) Reset() {
	*x = SuspendRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendRequest) ProtoMessage() {}

func (x *SuspendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendRequest.ProtoReflect.Descriptor instead.
func (*SuspendRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{20}
}

func (x *SuspendRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SuspendRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *SuspendRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type SuspendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendResponse) Reset() {
	*x = SuspendResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendResponse) ProtoMessage() {}

func (x *SuspendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendResponse.ProtoReflect.Descriptor instead.
func (*SuspendResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{21}
}

func (x *SuspendResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// ResumeRequest asks the agent to resume a suspended background (guest) job.
// Epoch fencing is the same as for SuspendRequest.
type ResumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier for the job, unique per agent.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// epoch fences late or duplicate calls (see SuspendRequest).
	Epoch int64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// deadline is the absolute time by which the operation must finish.
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{22}
}

func (x *ResumeRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ResumeRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ResumeRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type ResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeResponse) Reset() {
	*x = ResumeResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeResponse) ProtoMessage() {}

func (x *ResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeResponse.ProtoReflect.Descriptor instead.
func (*ResumeResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{23}
}

func (x *ResumeResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// KillRequest asks the agent to kill every process of a job. Kill has no
// epoch and works from any job state.
type KillRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier for the job, unique per agent.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// deadline is the absolute time by which the kill must be confirmed.
	Deadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// reason is a free-form explanation recorded by the agent.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{24}
}

func (x *KillRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *KillRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *KillRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{25}
}

func (x *KillResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{26}
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status OperationStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=snapshot_agent.v1alpha1.OperationStatus" json:"status,omitempty"`
	// storage_bytes is set on COMPLETE
	StorageBytes *int64 `protobuf:"varint,2,opt,name=storage_bytes,json=storageBytes,proto3,oneof" json:"storage_bytes,omitempty"`
	// snapshot_device_bytes is set on COMPLETE
	SnapshotDeviceBytes *int64 `protobuf:"varint,3,opt,name=snapshot_device_bytes,json=snapshotDeviceBytes,proto3,oneof" json:"snapshot_device_bytes,omitempty"`
	ElapsedMs           int64  `protobuf:"varint,4,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	// error is set on FAILED
	Error *string `protobuf:"bytes,5,opt,name=error,proto3,oneof" json:"error,omitempty"`
	// outcome is set on COMPLETE for Suspend, Resume and Kill operations.
	Outcome Outcome `protobuf:"varint,6,opt,name=outcome,proto3,enum=snapshot_agent.v1alpha1.Outcome" json:"outcome,omitempty"`
	// error_reason is set on FAILED for Suspend, Resume and Kill operations.
	ErrorReason ErrorReason `protobuf:"varint,7,opt,name=error_reason,json=errorReason,proto3,enum=snapshot_agent.v1alpha1.ErrorReason" json:"error_reason,omitempty"`
	// host_bytes_pinned is the host memory the job holds after the operation.
	HostBytesPinned int64 `protobuf:"varint,8,opt,name=host_bytes_pinned,json=hostBytesPinned,proto3" json:"host_bytes_pinned,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{27}
}

func (x *GetOperationResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *GetOperationResponse) GetStorageBytes() int64 {
	if x != nil && x.StorageBytes != nil {
		return *x.StorageBytes
	}
	return 0
}

func (x *GetOperationResponse) GetSnapshotDeviceBytes() int64 {
	if x != nil && x.SnapshotDeviceBytes != nil {
		return *x.SnapshotDeviceBytes
	}
	return 0
}

func (x *GetOperationResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *GetOperationResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetOperationResponse) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *GetOperationResponse) GetErrorReason() ErrorReason {
	if x != nil {
		return x.ErrorReason
	}
	return ErrorReason_ERROR_REASON_UNSPECIFIED
}

func (x *GetOperationResponse) GetHostBytesPinned() int64 {
	if x != nil {
		return x.HostBytesPinned
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{28}
}

type JobStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=snapshot_agent.v1alpha1.JobState" json:"state,omitempty"`
	// last_outcome is the outcome of the job's last completed operation
	// (OUTCOME_KILLED after a confirmed Kill).
	LastOutcome     Outcome `protobuf:"varint,3,opt,name=last_outcome,json=lastOutcome,proto3,enum=snapshot_agent.v1alpha1.Outcome" json:"last_outcome,omitempty"`
	DeviceBytes     int64   `protobuf:"varint,4,opt,name=device_bytes,json=deviceBytes,proto3" json:"device_bytes,omitempty"`
	HostBytesPinned int64   `protobuf:"varint,5,opt,name=host_bytes_pinned,json=hostBytesPinned,proto3" json:"host_bytes_pinned,omitempty"`
	// epoch is the last epoch seen for the job.
	Epoch         int64 `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_snapshot_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{29}
}

func (x *JobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatus) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobStatus) GetLastOutcome() Outcome {
	if x != nil {
		return x.LastOutcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *JobStatus) GetDeviceBytes() int64 {
	if x != nil {
		return x.DeviceBytes
	}
	return 0
}

func (x *JobStatus) GetHostBytesPinned() int64 {
	if x != nil {
		return x.HostBytesPinned
	}
	return 0
}

func (x *JobStatus) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type AcceleratorStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemoryUsedBytes  int64                  `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes int64                  `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AcceleratorStatus) Reset() {
	*x = AcceleratorStatus{}
	mi := &file_snapshot_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceleratorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceleratorStatus) ProtoMessage() {}

func (x *AcceleratorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceleratorStatus.ProtoReflect.Descriptor instead.
func (*AcceleratorStatus) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{30}
}

func (x *AcceleratorStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AcceleratorStatus) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *AcceleratorStatus) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

type StatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	JobStatuses         []*JobStatus           `protobuf:"bytes,1,rep,name=job_statuses,json=jobStatuses,proto3" json:"job_statuses,omitempty"`
	AcceleratorStatuses []*AcceleratorStatus   `protobuf:"bytes,2,rep,name=accelerator_statuses,json=acceleratorStatuses,proto3" json:"accelerator_statuses,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{31}
}

func (x *StatusResponse) GetJobStatuses() []*JobStatus {
	if x != nil {
		return x.JobStatuses
	}
	return nil
}

func (x *StatusResponse) GetAcceleratorStatuses() []*AcceleratorStatus {
	if x != nil {
		return x.AcceleratorStatuses
	}
	return nil
}

var File_snapshot_agent_proto protoreflect.FileDescriptor

const file_snapshot_agent_proto_rawDesc = "" +
	"\n" +
	"\x14snapshot_agent.proto\x12\x17snapshot_agent.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n" +
	"\rProcessTarget\x12\x12\n" +
	"\x04pids\x18\x01 \x03(\x05R\x04pids\"d\n" +
	"\x11CudaBackendConfig\x12O\n" +
	"\x0fexplicit_target\x18\x01 \x01(\v2&.snapshot_agent.v1alpha1.ProcessTargetR\x0eexplicitTarget\"l\n" +
	"\x19DirectMemoryBackendConfig\x12O\n" +
	"\x0fexplicit_target\x18\x01 \x01(\v2&.snapshot_agent.v1alpha1.ProcessTargetR\x0eexplicitTarget\"c\n" +
	"\x10TpuBackendConfig\x12O\n" +
	"\x0fexplicit_target\x18\x01 \x01(\v2&.snapshot_agent.v1alpha1.ProcessTargetR\x0eexplicitTarget\"\xaf\x01\n" +
	"\x11AppEndpointConfig\x12.\n" +
	"\x03app\x18\x01 \x01(\x0e2\x1c.snapshot_agent.v1alpha1.AppR\x03app\x12\x1c\n" +
	"\tendpoints\x18\x02 \x03(\tR\tendpoints\x128\n" +
	"\x04mode\x18\x03 \x01(\x0e2$.snapshot_agent.v1alpha1.SuspendModeR\x04mode\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"`\n" +
	"\x10AppChannelConfig\x128\n" +
	"\x04mode\x18\x01 \x01(\x0e2$.snapshot_agent.v1alpha1.SuspendModeR\x04mode\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"Y\n" +
	"\fMemoryRegion\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\x04R\aaddress\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\"\x82\x01\n" +
	"\x1aMemoryRegionsBackendConfig\x12?\n" +
	"\aregions\x18\x01 \x03(\v2%.snapshot_agent.v1alpha1.MemoryRegionR\aregions\x12#\n" +
	"\rsnapshot_name\x18\x02 \x01(\tR\fsnapshotName\"\xf3\x03\n" +
	"\rBackendConfig\x12@\n" +
	"\x04cuda\x18\x01 \x01(\v2*.snapshot_agent.v1alpha1.CudaBackendConfigH\x00R\x04cuda\x12O\n" +
	"\fapp_endpoint\x18\x02 \x01(\v2*.snapshot_agent.v1alpha1.AppEndpointConfigH\x00R\vappEndpoint\x12L\n" +
	"\vapp_channel\x18\x03 \x01(\v2).snapshot_agent.v1alpha1.AppChannelConfigH\x00R\n" +
	"appChannel\x12Y\n" +
	"\rdirect_memory\x18\x04 \x01(\v22.snapshot_agent.v1alpha1.DirectMemoryBackendConfigH\x00R\fdirectMemory\x12\\\n" +
	"\x0ememory_regions\x18\x05 \x01(\v23.snapshot_agent.v1alpha1.MemoryRegionsBackendConfigH\x00R\rmemoryRegions\x12=\n" +
	"\x03tpu\x18\x06 \x01(\v2).snapshot_agent.v1alpha1.TpuBackendConfigH\x00R\x03tpuB\t\n" +
	"\abackend\"\xc2\x01\n" +
	"\x14WorkloadCapabilities\x12M\n" +
	"\x0fsupported_modes\x18\x01 \x03(\x0e2$.snapshot_agent.v1alpha1.SuspendModeR\x0esupportedModes\x12G\n" +
	"\fdefault_mode\x18\x02 \x01(\x0e2$.snapshot_agent.v1alpha1.SuspendModeR\vdefaultMode\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"\x92\x01\n" +
	"\x10RegisterWorkload\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12Q\n" +
	"\fcapabilities\x18\x03 \x01(\v2-.snapshot_agent.v1alpha1.WorkloadCapabilitiesR\fcapabilities\"T\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa7\x01\n" +
	"\x0fWorkloadMessage\x12G\n" +
	"\bregister\x18\x01 \x01(\v2).snapshot_agent.v1alpha1.RegisterWorkloadH\x00R\bregister\x12@\n" +
	"\x06result\x18\x02 \x01(\v2&.snapshot_agent.v1alpha1.CommandResultH\x00R\x06resultB\t\n" +
	"\amessage\"_\n" +
	"\x0fSnapshotCommand\x128\n" +
	"\x04mode\x18\x01 \x01(\x0e2$.snapshot_agent.v1alpha1.SuspendModeR\x04mode\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"$\n" +
	"\x0eRestoreCommand\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"\xc5\x01\n" +
	"\fAgentCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12F\n" +
	"\bsnapshot\x18\x02 \x01(\v2(.snapshot_agent.v1alpha1.SnapshotCommandH\x00R\bsnapshot\x12C\n" +
	"\arestore\x18\x03 \x01(\v2'.snapshot_agent.v1alpha1.RestoreCommandH\x00R\arestoreB\t\n" +
	"\acommand\"\x85\x02\n" +
	"\x0fSnapshotRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12>\n" +
	"\abackend\x18\x03 \x01(\x0e2 .snapshot_agent.v1alpha1.BackendB\x02\x18\x01R\abackend\x12M\n" +
	"\x0ebackend_config\x18\x04 \x01(\v2&.snapshot_agent.v1alpha1.BackendConfigR\rbackendConfig\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"5\n" +
	"\x10SnapshotResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"\x84\x02\n" +
	"\x0eRestoreRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12>\n" +
	"\abackend\x18\x03 \x01(\x0e2 .snapshot_agent.v1alpha1.BackendB\x02\x18\x01R\abackend\x12M\n" +
	"\x0ebackend_config\x18\x04 \x01(\v2&.snapshot_agent.v1alpha1.BackendConfigR\rbackendConfig\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"4\n" +
	"\x0fRestoreResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"u\n" +
	"\x0eSuspendRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x126\n" +
	"\bdeadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"4\n" +
	"\x0fSuspendResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"t\n" +
	"\rResumeRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x126\n" +
	"\bdeadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"3\n" +
	"\x0eResumeResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"t\n" +
	"\vKillRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x126\n" +
	"\bdeadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"1\n" +
	"\fKillResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"8\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"\xdc\x03\n" +
	"\x14GetOperationResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.snapshot_agent.v1alpha1.OperationStatusR\x06status\x12(\n" +
	"\rstorage_bytes\x18\x02 \x01(\x03H\x00R\fstorageBytes\x88\x01\x01\x127\n" +
	"\x15snapshot_device_bytes\x18\x03 \x01(\x03H\x01R\x13snapshotDeviceBytes\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x04 \x01(\x03R\telapsedMs\x12\x19\n" +
	"\x05error\x18\x05 \x01(\tH\x02R\x05error\x88\x01\x01\x12:\n" +
	"\aoutcome\x18\x06 \x01(\x0e2 .snapshot_agent.v1alpha1.OutcomeR\aoutcome\x12G\n" +
	"\ferror_reason\x18\a \x01(\x0e2$.snapshot_agent.v1alpha1.ErrorReasonR\verrorReason\x12*\n" +
	"\x11host_bytes_pinned\x18\b \x01(\x03R\x0fhostBytesPinnedB\x10\n" +
	"\x0e_storage_bytesB\x18\n" +
	"\x16_snapshot_device_bytesB\b\n" +
	"\x06_error\"\x0f\n" +
	"\rStatusRequest\"\x85\x02\n" +
	"\tJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x127\n" +
	"\x05state\x18\x02 \x01(\x0e2!.snapshot_agent.v1alpha1.JobStateR\x05state\x12C\n" +
	"\flast_outcome\x18\x03 \x01(\x0e2 .snapshot_agent.v1alpha1.OutcomeR\vlastOutcome\x12!\n" +
	"\fdevice_bytes\x18\x04 \x01(\x03R\vdeviceBytes\x12*\n" +
	"\x11host_bytes_pinned\x18\x05 \x01(\x03R\x0fhostBytesPinned\x12\x14\n" +
	"\x05epoch\x18\x06 \x01(\x03R\x05epoch\"}\n" +
	"\x11AcceleratorStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x03R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x03R\x10memoryTotalBytes\"\xb6\x01\n" +
	"\x0eStatusResponse\x12E\n" +
	"\fjob_statuses\x18\x01 \x03(\v2\".snapshot_agent.v1alpha1.JobStatusR\vjobStatuses\x12]\n" +
	"\x14accelerator_statuses\x18\x02 \x03(\v2*.snapshot_agent.v1alpha1.AcceleratorStatusR\x13acceleratorStatuses*8\n" +
	"\aBackend\x12\x17\n" +
	"\x13BACKEND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fBACKEND_CUDA\x10\x01\x1a\x02\x18\x01*8\n" +
	"\x03App\x12\x13\n" +
	"\x0fAPP_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bAPP_VLLM\x10\x01\x12\x0e\n" +
	"\n" +
	"APP_SGLANG\x10\x02*_\n" +
	"\vSuspendMode\x12\x1c\n" +
	"\x18SUSPEND_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SUSPEND_MODE_OFFLOAD\x10\x01\x12\x18\n" +
	"\x14SUSPEND_MODE_DISCARD\x10\x02*x\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11OUTCOME_SUSPENDED\x10\x01\x12\x14\n" +
	"\x10OUTCOME_RELEASED\x10\x02\x12\x13\n" +
	"\x0fOUTCOME_RESUMED\x10\x03\x12\x12\n" +
	"\x0eOUTCOME_KILLED\x10\x04*\x8d\x02\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x18ERROR_REASON_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DEADLINE_INFEASIBLE\x10\x01\x12\x15\n" +
	"\x11DEADLINE_EXCEEDED\x10\x02\x12\x0f\n" +
	"\vSTALE_EPOCH\x10\x03\x12\x1a\n" +
	"\x16PRECONDITION_READINESS\x10\x04\x12\x17\n" +
	"\x13PRECONDITION_PROBES\x10\x05\x12\x17\n" +
	"\x13PRECONDITION_MEMORY\x10\x06\x12\x15\n" +
	"\x11PRECONDITION_NODE\x10\a\x12\x11\n" +
	"\rBACKEND_ERROR\x10\b\x12\x11\n" +
	"\rVERIFY_FAILED\x10\t\x12\x14\n" +
	"\x10KILL_UNCONFIRMED\x10\n" +
	"*\x8d\x01\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATION_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19OPERATION_STATUS_COMPLETE\x10\x02\x12\x1b\n" +
	"\x17OPERATION_STATUS_FAILED\x10\x03*\xb2\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eJOB_STATE_IDLE\x10\x01\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x02\x12\x1b\n" +
	"\x17JOB_STATE_TRANSITIONING\x10\x03\x12\x13\n" +
	"\x0fJOB_STATE_SAVED\x10\x04\x12\x15\n" +
	"\x11JOB_STATE_FAULTED\x10\x05\x12\x17\n" +
	"\x13JOB_STATE_SUSPENDED\x10\x062\x93\x06\n" +
	"\x14SnapshotAgentService\x12_\n" +
	"\bSnapshot\x12(.snapshot_agent.v1alpha1.SnapshotRequest\x1a).snapshot_agent.v1alpha1.SnapshotResponse\x12\\\n" +
	"\aRestore\x12'.snapshot_agent.v1alpha1.RestoreRequest\x1a(.snapshot_agent.v1alpha1.RestoreResponse\x12k\n" +
	"\fGetOperation\x12,.snapshot_agent.v1alpha1.GetOperationRequest\x1a-.snapshot_agent.v1alpha1.GetOperationResponse\x12Y\n" +
	"\x06Status\x12&.snapshot_agent.v1alpha1.StatusRequest\x1a'.snapshot_agent.v1alpha1.StatusResponse\x12f\n" +
	"\x0fWorkloadChannel\x12(.snapshot_agent.v1alpha1.WorkloadMessage\x1a%.snapshot_agent.v1alpha1.AgentCommand(\x010\x01\x12\\\n" +
	"\aSuspend\x12'.snapshot_agent.v1alpha1.SuspendRequest\x1a(.snapshot_agent.v1alpha1.SuspendResponse\x12Y\n" +
	"\x06Resume\x12&.snapshot_agent.v1alpha1.ResumeRequest\x1a'.snapshot_agent.v1alpha1.ResumeResponse\x12S\n" +
	"\x04Kill\x12$.snapshot_agent.v1alpha1.KillRequest\x1a%.snapshot_agent.v1alpha1.KillResponseB\\ZZgithub.com/llm-d-incubation/llm-d-rl-time-slicing/pkg/snapshot-agent/api/v1alpha1;v1alpha1b\x06proto3"

var (
	file_snapshot_agent_proto_rawDescOnce sync.Once
	file_snapshot_agent_proto_rawDescData []byte
)

func file_snapshot_agent_proto_rawDescGZIP() []byte {
	file_snapshot_agent_proto_rawDescOnce.Do(func() {
		file_snapshot_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_agent_proto_rawDesc), len(file_snapshot_agent_proto_rawDesc)))
	})
	return file_snapshot_agent_proto_rawDescData
}

var file_snapshot_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_snapshot_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_snapshot_agent_proto_goTypes = []any{
	(Backend)(0),                       // 0: snapshot_agent.v1alpha1.Backend
	(App)(0),                           // 1: snapshot_agent.v1alpha1.App
	(SuspendMode)(0),                   // 2: snapshot_agent.v1alpha1.SuspendMode
	(Outcome)(0),                       // 3: snapshot_agent.v1alpha1.Outcome
	(ErrorReason)(0),                   // 4: snapshot_agent.v1alpha1.ErrorReason
	(OperationStatus)(0),               // 5: snapshot_agent.v1alpha1.OperationStatus
	(JobState)(0),                      // 6: snapshot_agent.v1alpha1.JobState
	(*ProcessTarget)(nil),              // 7: snapshot_agent.v1alpha1.ProcessTarget
	(*CudaBackendConfig)(nil),          // 8: snapshot_agent.v1alpha1.CudaBackendConfig
	(*DirectMemoryBackendConfig)(nil),  // 9: snapshot_agent.v1alpha1.DirectMemoryBackendConfig
	(*TpuBackendConfig)(nil),           // 10: snapshot_agent.v1alpha1.TpuBackendConfig
	(*AppEndpointConfig)(nil),          // 11: snapshot_agent.v1alpha1.AppEndpointConfig
	(*AppChannelConfig)(nil),           // 12: snapshot_agent.v1alpha1.AppChannelConfig
	(*MemoryRegion)(nil),               // 13: snapshot_agent.v1alpha1.MemoryRegion
	(*MemoryRegionsBackendConfig)(nil), // 14: snapshot_agent.v1alpha1.MemoryRegionsBackendConfig
	(*BackendConfig)(nil),              // 15: snapshot_agent.v1alpha1.BackendConfig
	(*WorkloadCapabilities)(nil),       // 16: snapshot_agent.v1alpha1.WorkloadCapabilities
	(*RegisterWorkload)(nil),           // 17: snapshot_agent.v1alpha1.RegisterWorkload
	(*CommandResult)(nil),              // 18: snapshot_agent.v1alpha1.CommandResult
	(*WorkloadMessage)(nil),            // 19: snapshot_agent.v1alpha1.WorkloadMessage
	(*SnapshotCommand)(nil),            // 20: snapshot_agent.v1alpha1.SnapshotCommand
	(*RestoreCommand)(nil),             // 21: snapshot_agent.v1alpha1.RestoreCommand
	(*AgentCommand)(nil),               // 22: snapshot_agent.v1alpha1.AgentCommand
	(*SnapshotRequest)(nil),            // 23: snapshot_agent.v1alpha1.SnapshotRequest
	(*SnapshotResponse)(nil),           // 24: snapshot_agent.v1alpha1.SnapshotResponse
	(*RestoreRequest)(nil),             // 25: snapshot_agent.v1alpha1.RestoreRequest
	(*RestoreResponse)(nil),            // 26: snapshot_agent.v1alpha1.RestoreResponse
	(*SuspendRequest)(nil),             // 27: snapshot_agent.v1alpha1.SuspendRequest
	(*SuspendResponse)(nil),            // 28: snapshot_agent.v1alpha1.SuspendResponse
	(*ResumeRequest)(nil),              // 29: snapshot_agent.v1alpha1.ResumeRequest
	(*ResumeResponse)(nil),             // 30: snapshot_agent.v1alpha1.ResumeResponse
	(*KillRequest)(nil),                // 31: snapshot_agent.v1alpha1.KillRequest
	(*KillResponse)(nil),               // 32: snapshot_agent.v1alpha1.KillResponse
	(*GetOperationRequest)(nil),        // 33: snapshot_agent.v1alpha1.GetOperationRequest
	(*GetOperationResponse)(nil),       // 34: snapshot_agent.v1alpha1.GetOperationResponse
	(*StatusRequest)(nil),              // 35: snapshot_agent.v1alpha1.StatusRequest
	(*JobStatus)(nil),                  // 36: snapshot_agent.v1alpha1.JobStatus
	(*AcceleratorStatus)(nil),          // 37: snapshot_agent.v1alpha1.AcceleratorStatus
	(*StatusResponse)(nil),             // 38: snapshot_agent.v1alpha1.StatusResponse
	(*timestamppb.Timestamp)(nil),      // 39: google.protobuf.Timestamp
}
var file_snapshot_agent_proto_depIdxs = []int32{
	7,  // 0: snapshot_agent.v1alpha1.CudaBackendConfig.explicit_target:type_name -> snapshot_agent.v1alpha1.ProcessTarget
	7,  // 1: snapshot_agent.v1alpha1.DirectMemoryBackendConfig.explicit_target:type_name -> snapshot_agent.v1alpha1.ProcessTarget
	7,  // 2: snapshot_agent.v1alpha1.TpuBackendConfig.explicit_target:type_name -> snapshot_agent.v1alpha1.ProcessTarget
	1,  // 3: snapshot_agent.v1alpha1.AppEndpointConfig.app:type_name -> snapshot_agent.v1alpha1.App
	2,  // 4: snapshot_agent.v1alpha1.AppEndpointConfig.mode:type_name -> snapshot_agent.v1alpha1.SuspendMode
	2,  // 5: snapshot_agent.v1alpha1.AppChannelConfig.mode:type_name -> snapshot_agent.v1alpha1.SuspendMode
	13, // 6: snapshot_agent.v1alpha1.MemoryRegionsBackendConfig.regions:type_name -> snapshot_agent.v1alpha1.MemoryRegion
	8,  // 7: snapshot_agent.v1alpha1.BackendConfig.cuda:type_name -> snapshot_agent.v1alpha1.CudaBackendConfig
	11, // 8: snapshot_agent.v1alpha1.BackendConfig.app_endpoint:type_name -> snapshot_agent.v1alpha1.AppEndpointConfig
	12, // 9: snapshot_agent.v1alpha1.BackendConfig.app_channel:type_name -> snapshot_agent.v1alpha1.AppChannelConfig
	9,  // 10: snapshot_agent.v1alpha1.BackendConfig.direct_memory:type_name -> snapshot_agent.v1alpha1.DirectMemoryBackendConfig
	14, // 11: snapshot_agent.v1alpha1.BackendConfig.memory_regions:type_name -> snapshot_agent.v1alpha1.MemoryRegionsBackendConfig
	10, // 12: snapshot_agent.v1alpha1.BackendConfig.tpu:type_name -> snapshot_agent.v1alpha1.TpuBackendConfig
	2,  // 13: snapshot_agent.v1alpha1.WorkloadCapabilities.supported_modes:type_name -> snapshot_agent.v1alpha1.SuspendMode
	2,  // 14: snapshot_agent.v1alpha1.WorkloadCapabilities.default_mode:type_name -> snapshot_agent.v1alpha1.SuspendMode
	16, // 15: snapshot_agent.v1alpha1.RegisterWorkload.capabilities:type_name -> snapshot_agent.v1alpha1.WorkloadCapabilities
	17, // 16: snapshot_agent.v1alpha1.WorkloadMessage.register:type_name -> snapshot_agent.v1alpha1.RegisterWorkload
	18, // 17: snapshot_agent.v1alpha1.WorkloadMessage.result:type_name -> snapshot_agent.v1alpha1.CommandResult
	2,  // 18: snapshot_agent.v1alpha1.SnapshotCommand.mode:type_name -> snapshot_agent.v1alpha1.SuspendMode
	20, // 19: snapshot_agent.v1alpha1.AgentCommand.snapshot:type_name -> snapshot_agent.v1alpha1.SnapshotCommand
	21, // 20: snapshot_agent.v1alpha1.AgentCommand.restore:type_name -> snapshot_agent.v1alpha1.RestoreCommand
	0,  // 21: snapshot_agent.v1alpha1.SnapshotRequest.backend:type_name -> snapshot_agent.v1alpha1.Backend
	15, // 22: snapshot_agent.v1alpha1.SnapshotRequest.backend_config:type_name -> snapshot_agent.v1alpha1.BackendConfig
	39, // 23: snapshot_agent.v1alpha1.SnapshotRequest.deadline:type_name -> google.protobuf.Timestamp
	0,  // 24: snapshot_agent.v1alpha1.RestoreRequest.backend:type_name -> snapshot_agent.v1alpha1.Backend
	15, // 25: snapshot_agent.v1alpha1.RestoreRequest.backend_config:type_name -> snapshot_agent.v1alpha1.BackendConfig
	39, // 26: snapshot_agent.v1alpha1.RestoreRequest.deadline:type_name -> google.protobuf.Timestamp
	39, // 27: snapshot_agent.v1alpha1.SuspendRequest.deadline:type_name -> google.protobuf.Timestamp
	39, // 28: snapshot_agent.v1alpha1.ResumeRequest.deadline:type_name -> google.protobuf.Timestamp
	39, // 29: snapshot_agent.v1alpha1.KillRequest.deadline:type_name -> google.protobuf.Timestamp
	5,  // 30: snapshot_agent.v1alpha1.GetOperationResponse.status:type_name -> snapshot_agent.v1alpha1.OperationStatus
	3,  // 31: snapshot_agent.v1alpha1.GetOperationResponse.outcome:type_name -> snapshot_agent.v1alpha1.Outcome
	4,  // 32: snapshot_agent.v1alpha1.GetOperationResponse.error_reason:type_name -> snapshot_agent.v1alpha1.ErrorReason
	6,  // 33: snapshot_agent.v1alpha1.JobStatus.state:type_name -> snapshot_agent.v1alpha1.JobState
	3,  // 34: snapshot_agent.v1alpha1.JobStatus.last_outcome:type_name -> snapshot_agent.v1alpha1.Outcome
	36, // 35: snapshot_agent.v1alpha1.StatusResponse.job_statuses:type_name -> snapshot_agent.v1alpha1.JobStatus
	37, // 36: snapshot_agent.v1alpha1.StatusResponse.accelerator_statuses:type_name -> snapshot_agent.v1alpha1.AcceleratorStatus
	23, // 37: snapshot_agent.v1alpha1.SnapshotAgentService.Snapshot:input_type -> snapshot_agent.v1alpha1.SnapshotRequest
	25, // 38: snapshot_agent.v1alpha1.SnapshotAgentService.Restore:input_type -> snapshot_agent.v1alpha1.RestoreRequest
	33, // 39: snapshot_agent.v1alpha1.SnapshotAgentService.GetOperation:input_type -> snapshot_agent.v1alpha1.GetOperationRequest
	35, // 40: snapshot_agent.v1alpha1.SnapshotAgentService.Status:input_type -> snapshot_agent.v1alpha1.StatusRequest
	19, // 41: snapshot_agent.v1alpha1.SnapshotAgentService.WorkloadChannel:input_type -> snapshot_agent.v1alpha1.WorkloadMessage
	27, // 42: snapshot_agent.v1alpha1.SnapshotAgentService.Suspend:input_type -> snapshot_agent.v1alpha1.SuspendRequest
	29, // 43: snapshot_agent.v1alpha1.SnapshotAgentService.Resume:input_type -> snapshot_agent.v1alpha1.ResumeRequest
	31, // 44: snapshot_agent.v1alpha1.SnapshotAgentService.Kill:input_type -> snapshot_agent.v1alpha1.KillRequest
	24, // 45: snapshot_agent.v1alpha1.SnapshotAgentService.Snapshot:output_type -> snapshot_agent.v1alpha1.SnapshotResponse
	26, // 46: snapshot_agent.v1alpha1.SnapshotAgentService.Restore:output_type -> snapshot_agent.v1alpha1.RestoreResponse
	34, // 47: snapshot_agent.v1alpha1.SnapshotAgentService.GetOperation:output_type -> snapshot_agent.v1alpha1.GetOperationResponse
	38, // 48: snapshot_agent.v1alpha1.SnapshotAgentService.Status:output_type -> snapshot_agent.v1alpha1.StatusResponse
	22, // 49: snapshot_agent.v1alpha1.SnapshotAgentService.WorkloadChannel:output_type -> snapshot_agent.v1alpha1.AgentCommand
	28, // 50: snapshot_agent.v1alpha1.SnapshotAgentService.Suspend:output_type -> snapshot_agent.v1alpha1.SuspendResponse
	30, // 51: snapshot_agent.v1alpha1.SnapshotAgentService.Resume:output_type -> snapshot_agent.v1alpha1.ResumeResponse
	32, // 52: snapshot_agent.v1alpha1.SnapshotAgentService.Kill:output_type -> snapshot_agent.v1alpha1.KillResponse
	45, // [45:53] is the sub-list for method output_type
	37, // [37:45] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_snapshot_agent_proto_init() }
func file_snapshot_agent_proto_init() {
	if File_snapshot_agent_proto != nil {
		return
	}
	file_snapshot_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*BackendConfig_Cuda)(nil),
		(*BackendConfig_AppEndpoint)(nil),
		(*BackendConfig_AppChannel)(nil),
		(*BackendConfig_DirectMemory)(nil),
		(*BackendConfig_MemoryRegions)(nil),
		(*BackendConfig_Tpu)(nil),
	}
	file_snapshot_agent_proto_msgTypes[12].OneofWrappers = []any{
		(*WorkloadMessage_Register)(nil),
		(*WorkloadMessage_Result)(nil),
	}
	file_snapshot_agent_proto_msgTypes[15].OneofWrappers = []any{
		(*AgentCommand_Snapshot)(nil),
		(*AgentCommand_Restore)(nil),
	}
	file_snapshot_agent_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_agent_proto_rawDesc), len(file_snapshot_agent_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snapshot_agent_proto_goTypes,
		DependencyIndexes: file_snapshot_agent_proto_depIdxs,
		EnumInfos:         file_snapshot_agent_proto_enumTypes,
		MessageInfos:      file_snapshot_agent_proto_msgTypes,
	}.Build()
	File_snapshot_agent_proto = out.File
	file_snapshot_agent_proto_goTypes = nil
	file_snapshot_agent_proto_depIdxs = nil
}
