{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "guest-kubelet.serviceAccountName" . }}
  namespace: {{ include "guest-kubelet.namespace" . }}
  labels:
    {{- include "guest-kubelet.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
