// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: host_command.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostCommandService_Vacate_FullMethodName = "/timeslice_hostcommand.v1alpha1.HostCommandService/Vacate"
	HostCommandService_Resume_FullMethodName = "/timeslice_hostcommand.v1alpha1.HostCommandService/Resume"
)

// HostCommandServiceClient is the client API for HostCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostCommandService is served by the per-host component of a shared host
// (the virtual kubelet) at <node InternalIP>:<host command port>. The
// orchestrator is its only caller.
//
// On a foreground Acquire the orchestrator sends Vacate to every host of the
// group, waits until every host has acked OUTCOME_VACATED, and only then
// grants the foreground. On a foreground Yield that lends the accelerator it
// sends Resume to every host.
//
// Every command carries an epoch. Epochs increase strictly across commands,
// also across orchestrator restarts. A host keeps the highest epoch it has
// seen and answers a command with a lower epoch with OUTCOME_STALE_EPOCH
// without acting on it. A command with a higher epoch supersedes a running
// command of the other kind (a Vacate aborts a running Resume). A Vacate with
// a higher epoch while a Vacate is already running joins it: the host acks the
// new epoch when the running vacate finishes.
//
// Both RPCs return only when the command is done: the response is the ack.
// Commands are idempotent: a Vacate on a host with nothing to vacate acks
// OUTCOME_VACATED at once.
type HostCommandServiceClient interface {
	// Vacate makes the host stop every guest on it: for each guest, mark it not
	// ready and confirm that, then suspend it, all before deadline. It returns
	// OUTCOME_VACATED only when every guest is suspended.
	Vacate(ctx context.Context, in *VacateRequest, opts ...grpc.CallOption) (*HostAck, error)
	// Resume lets the host run its guests again: for each suspended guest,
	// resume it and then mark it ready.
	Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*HostAck, error)
}

type hostCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostCommandServiceClient(cc grpc.ClientConnInterface) HostCommandServiceClient {
	return &hostCommandServiceClient{cc}
}

func (c *hostCommandServiceClient) Vacate(ctx context.Context, in *VacateRequest, opts ...grpc.CallOption) (*HostAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostAck)
	err := c.cc.Invoke(ctx, HostCommandService_Vacate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostCommandServiceClient) Resume(ctx context.Context, in *ResumeRequest, opts ...grpc.CallOption) (*HostAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostAck)
	err := c.cc.Invoke(ctx, HostCommandService_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostCommandServiceServer is the server API for HostCommandService service.
// All implementations must embed UnimplementedHostCommandServiceServer
// for forward compatibility.
//
// HostCommandService is served by the per-host component of a shared host
// (the virtual kubelet) at <node InternalIP>:<host command port>. The
// orchestrator is its only caller.
//
// On a foreground Acquire the orchestrator sends Vacate to every host of the
// group, waits until every host has acked OUTCOME_VACATED, and only then
// grants the foreground. On a foreground Yield that lends the accelerator it
// sends Resume to every host.
//
// Every command carries an epoch. Epochs increase strictly across commands,
// also across orchestrator restarts. A host keeps the highest epoch it has
// seen and answers a command with a lower epoch with OUTCOME_STALE_EPOCH
// without acting on it. A command with a higher epoch supersedes a running
// command of the other kind (a Vacate aborts a running Resume). A Vacate with
// a higher epoch while a Vacate is already running joins it: the host acks the
// new epoch when the running vacate finishes.
//
// Both RPCs return only when the command is done: the response is the ack.
// Commands are idempotent: a Vacate on a host with nothing to vacate acks
// OUTCOME_VACATED at once.
type HostCommandServiceServer interface {
	// Vacate makes the host stop every guest on it: for each guest, mark it not
	// ready and confirm that, then suspend it, all before deadline. It returns
	// OUTCOME_VACATED only when every guest is suspended.
	Vacate(context.Context, *VacateRequest) (*HostAck, error)
	// Resume lets the host run its guests again: for each suspended guest,
	// resume it and then mark it ready.
	Resume(context.Context, *ResumeRequest) (*HostAck, error)
	mustEmbedUnimplementedHostCommandServiceServer()
}

// UnimplementedHostCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostCommandServiceServer struct{}

func (UnimplementedHostCommandServiceServer) Vacate(context.Context, *VacateRequest) (*HostAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Vacate not implemented")
}
func (UnimplementedHostCommandServiceServer) Resume(context.Context, *ResumeRequest) (*HostAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedHostCommandServiceServer) mustEmbedUnimplementedHostCommandServiceServer() {}
func (UnimplementedHostCommandServiceServer) testEmbeddedByValue()                            {}

// UnsafeHostCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostCommandServiceServer will
// result in compilation errors.
type UnsafeHostCommandServiceServer interface {
	mustEmbedUnimplementedHostCommandServiceServer()
}

func RegisterHostCommandServiceServer(s grpc.ServiceRegistrar, srv HostCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedHostCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostCommandService_ServiceDesc, srv)
}

func _HostCommandService_Vacate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VacateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostCommandServiceServer).Vacate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostCommandService_Vacate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostCommandServiceServer).Vacate(ctx, req.(*VacateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostCommandService_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostCommandServiceServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostCommandService_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostCommandServiceServer).Resume(ctx, req.(*ResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostCommandService_ServiceDesc is the grpc.ServiceDesc for HostCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "timeslice_hostcommand.v1alpha1.HostCommandService",
	HandlerType: (*HostCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Vacate",
			Handler:    _HostCommandService_Vacate_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _HostCommandService_Resume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "host_command.proto",
}
